chess_openings/chess_openings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('chs.urls', namespace='chess')),
    url(r'^admin/', admin.site.urls),
]

chess_openings/chs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.mainpage,
        name='mainpage'),
    url(r'^game/(?P<pk>[0-9]+)/$',
        views.GameDetail.as_view(),
        name='game'),
    url(r'^game/$',
        views.GameList.as_view(),
        name='game_list'),
    url(r'^game/search/$', views.search_game, name='game_search'),
    url(r'^game/create/$', views.create_game, name='game_create'),
    url(r'^game/add/$', views.add_game, name='game_add'),
    url(r'^game/add/pgn/$', views.add_game_pgn, name='game_add_pgn'),
    url(r'^game/edit/(?P<pk>[0-9]+)/$', views.edit_game, name='game_edit'),
    url(r'^game/delete/(?P<pk>[0-9]+)/$', views.delete_game, name='game_delete'),
    url(r'^player/(?P<pk>[0-9]+)/$',
        views.PlayerDetail.as_view(),
        name='player'),
    url(r'^player/$',
        views.PlayerList.as_view(),
        name='player_list'),
    url(r'^player/search/$', views.search_player, name='player_search'),
    url(r'^player/create/$', views.create_player, name='player_create'),
    url(r'^player/add/$', views.add_player, name='player_add'),
    url(r'^player/edit/(?P<pk>[0-9]+)/$', views.edit_player, name='player_edit'),
    url(r'^player/delete/(?P<pk>[0-9]+)/$', views.delete_player, name='player_delete'),
    url(r'^event/(?P<pk>[0-9]+)/$',
        views.EventDetail.as_view(),
        name='event'),
    url(r'^event/$',
        views.EventList.as_view(),
        name='event_list'),
    url(r'^event/search/$', views.search_event, name='event_search'),
    url(r'^event/create/$', views.create_event, name='event_create'),
    url(r'^event/add/$', views.add_event, name='event_add'),
    url(r'^event/edit/(?P<pk>[0-9]+)/$', views.edit_event, name='event_edit'),
    url(r'^event/delete/(?P<pk>[0-9]+)/$', views.delete_event, name='event_delete'),
    url(r'^opening/(?P<pk>[0-9]+)/$',
        views.OpeningDetail.as_view(),
        name='opening'),
    url(r'^opening/$',
        views.OpeningList.as_view(),
        name='opening_list'),
    url(r'^opening/search/$', views.search_opening, name='opening_search'),
    url(r'^opening/create/$', views.create_opening, name='opening_create'),
    url(r'^opening/add/$', views.add_opening, name='opening_add'),
    url(r'^opening/edit/(?P<pk>[0-9]+)/$', views.edit_opening, name='opening_edit'),
    url(r'^opening/delete/(?P<pk>[0-9]+)/$', views.delete_opening, name='opening_delete'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.object,
        name='object'),
    url(r'^comment/(?P<pk>[0-9]+)/$',
        views.comment,
        name="comment"),
    url(r'^login/$',
        views.login,
        name="login"),
    url(r'^login/handle/$',
        views.handle_login,
        name="handle_login"),
    url(r'^logout/$',
        views.logout,
        name="logout"),
    url(r'^register/$',
        views.register,
        name="register"),
    url(r'^register/handle/$',
        views.handle_register,
        name="handle_register"),
    url(r'^account/$',
        views.account,
        name="account"),
    url(r'^account/change_password$',
        views.change_password,
        name="change_password")
]

chess_openings/chs/views.py
from django.http import Http404, HttpResponseRedirect
from django.views import generic
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.db.models.sql.constants import INNER, LOUTER
from . import pgn

from . import models

import hashlib
import os


def pagination_links(current, total):
    """Creates a list of page numbers to link to."""
    adjacent_links_per_side = 2
    distant_links_per_side = 3

    left_adjacent = current - adjacent_links_per_side
    right_adjacent = current + adjacent_links_per_side

    left_distant_pages = left_adjacent - 1
    right_distant_pages = total - right_adjacent
    left_step = max(1, left_distant_pages // distant_links_per_side)
    right_step = max(1, right_distant_pages // distant_links_per_side)

    left = list(range(1, left_adjacent, left_step))
    middle = list(range(max(1, left_adjacent), min(total, right_adjacent) + 1))
    right = list(range(total, right_adjacent, -right_step))
    right.reverse()

    return left + middle + right


class PaginatedListView(generic.ListView):
    def get_context_data(self, **kwargs):
        context = super(PaginatedListView, self).get_context_data(**kwargs)
        if context['paginator']:
            current = context['page_obj'].number
            total = context['paginator'].num_pages
            context['page_links'] = pagination_links(current, total)
        return context


def can_edit(session, object):
    return ('account' in session and session['account']
            and models.has_edit_rights(session['account'], object))


class GameDetail(generic.DetailView):
    model = models.Game

    def get_context_data(self, **kwargs):
        context = super(GameDetail, self).get_context_data(**kwargs)
        context['openings'] = context['game'].openings()
        context['can_edit'] = can_edit(self.request.session, context['game'])
        return context


class PlayerDetail(generic.DetailView):
    model = models.Player

    def get_context_data(self, **kwargs):
        context = super(PlayerDetail, self).get_context_data(**kwargs)
        context['player_games'] = context['player'].games()[:50]
        context['can_edit'] = can_edit(self.request.session, context['player'])
        return context


class EventDetail(generic.DetailView):
    model = models.Event

    def get_context_data(self, **kwargs):
        context = super(EventDetail, self).get_context_data(**kwargs)
        context['event_games'] = context['event'].games()[:50]
        context['can_edit'] = can_edit(self.request.session, context['event'])
        return context


class OpeningDetail(generic.DetailView):
    model = models.Opening

    def get_context_data(self, **kwargs):
        context = super(OpeningDetail, self).get_context_data(**kwargs)
        opening = context['opening']
        context['opening_games'] = opening.games()[:50]
        context['variations'] = opening.variations()
        context['variation_of'] = opening.variation_of()
        context['can_edit'] = can_edit(self.request.session, opening)
        return context


# This is a big hack to get django to get django to do a weird join.
# The problem is with queries like 'games where either player is ...'.
# Such queries are best done with a single join :
#   chs_game JOIN chs_player ON
#   white_id = chs_player.object_id OR black_id = chs_player.object_id
#
# Unfortunaly, django is really not designed to do joins with strange
# conditions, such as join conditions with an OR.
# Equivalent queries that can easily be expressed through django are
# heavily inefficient (~10 times slower during my tests).

# This class is a hacked version of `django.db.models.sql.datastructures.Join`
# which is used has a join descriptor by `django.db.models.sql.query.Query`.
# It is responsible for producing the SQL code associated with the join,
# making it easy to change in order to do a custom join condition.
class PlayerLookupJoin(object):
    def __init__(self, parent_alias, condition, params):
        # Join table
        self.table_name = 'chs_player'
        self.parent_alias = parent_alias
        # Note: table_alias is not necessarily known at instantiation time.
        self.table_alias = None
        # LOUTER or INNER
        self.join_type = INNER
        # Is this join nullabled?
        self.nullable = False
        # Custom join condition. Takes the table alias to use as parameters.
        self.condition = condition
        # parameters for join condition
        self.params = params

    def as_sql(self, compiler, connection):
        qn = compiler.quote_name_unless_alias

        condition = '%s.white_id = %s.object_id OR %s.black_id = %s.object_id'
        condition = condition % (
            qn(self.parent_alias),
            qn(self.table_alias),
            qn(self.parent_alias),
            qn(self.table_alias),
        )

        custom_condition = self.condition(qn(self.table_alias))
        params = self.params

        on_clause_sql = '(%s) AND (%s)' % (condition, custom_condition)

        alias_str = '' if self.table_alias == self.table_name else (' %s' % self.table_alias)
        sql = '%s %s%s ON (%s)' % (self.join_type, qn(self.table_name), alias_str, on_clause_sql)
        return sql, params

    def relabeled_clone(self, change_map):
        new_parent_alias = change_map.get(self.parent_alias, self.parent_alias)
        new_table_alias = change_map.get(self.table_alias, self.table_alias)
        return self.__class__(
            self.table_name, new_parent_alias, new_table_alias, self.join_type,
            self.join_field, self.nullable)

    def __eq__(self, other):
        if isinstance(other, self.__class__):
            return (
                self.table_name == other.table_name and
                self.parent_alias == other.parent_alias
            )
        return False

    def demote(self):
        new = self.relabeled_clone({})
        new.join_type = INNER
        return new

    def promote(self):
        new = self.relabeled_clone({})
        new.join_type = LOUTER
        return new


class GameList(PaginatedListView):
    paginate_by = 50
    context_object_name = "game_list"

    def get_queryset(self):
        query = self.request.GET

        def is_set(attr):
            return attr in query and query[attr]

        result = models.Game.objects.all()
        if is_set('result'):
            result = result.filter(result=query['result'])
        if is_set('location'):
            result = result.filter(location__icontains=query['location'])
        if is_set('event'):
            result = result.filter(event__event_name__icontains=query['event'])
        if is_set('after'):
            result = result.filter(start_date__gte=query['after'])
        if is_set('before'):
            result = result.filter(start_date__lte=query['before'])
        if is_set('white'):
            result = result.filter(
                Q(white__lastname__icontains=query['white'])
                | Q(white__firstname__icontains=query['white'])
            )
        if is_set('white_nat'):
            result = result.filter(white__nationality=query['white_nat'])
        if is_set('white_elo_min'):
            result = result.filter(white__elo_rating__gte=query['white_elo_min'])
        if is_set('white_elo_max'):
            result = result.filter(white__elo_rating__lte=query['white_elo_max'])

        if is_set('black'):
            result = result.filter(
                Q(black__lastname__icontains=query['black'])
                | Q(black__firstname__icontains=query['black'])
            )
        if is_set('black_nat'):
            result = result.filter(white__nationality=query['black_nat'])
        if is_set('black_elo_min'):
            result = result.filter(black__elo_rating__gte=query['black_elo_min'])
        if is_set('black_elo_max'):
            result = result.filter(black__elo_rating__lte=query['black_elo_max'])

        if is_set('opening'):
            try:
                opening = models.Opening.objects.get(
                    opening_name=query['opening']
                )
                result = result.filter(moves__chs_startswith=opening.moves)
            except models.Opening.DoesNotExist:
                result = models.Game.objects.none()
        if is_set('moves'):
            moves = pgn.encode_moves_from_uci(query['moves'].split(','))
            result = result.filter(moves__chs_startswith=moves)

        if is_set('player'):
            def condition(table):
                sql = 'UPPER(%s.lastname) = UPPER(%s) OR UPPER(%s.firstname) = UPPER(%s)'
                return sql % (table, '%s', table, '%s')

            join = PlayerLookupJoin(
                result.query.get_initial_alias(),
                condition,
                [query['player'], query['player']]
            )
            result.query.join(join, [])
        if is_set('player_nat'):
            def condition(table):
                sql = '%s.nationality = %s'
                return sql % (table, '%s')

            join = PlayerLookupJoin(
                result.query.get_initial_alias(),
                condition,
                [query['player_nat']]
            )
            result.query.join(join, [])
        if is_set('player_elo_min'):
            def condition(table):
                sql = '%s.elo_rating >= %s'
                return sql % (table, '%s')

            join = PlayerLookupJoin(
                result.query.get_initial_alias(),
                condition,
                [query['player_elo_min']]
            )
            result.query.join(join, [])
        if is_set('player_elo_max'):
            def condition(table):
                sql = '%s.elo_rating <= %s'
                return sql % (table, '%s')

            join = PlayerLookupJoin(
                result.query.get_initial_alias(),
                condition,
                [query['player_elo_max']]

chess_openings/chs/templates/chs/event_create.html
{% extends "chs/base.html" %}

{% load staticfiles %}

{% block title %}create event{% endblock %}

{% block content %}
  <h1>Event {% if event %}Modification{% else %}Creation{% endif %}</h1>
  {% if request.session.account %}
    <form action="{% url 'chess:event_add' %}" method="post">
      <fieldset> <legend> Event {% if event %} modification : {% else %} creation{% endif %}</legend>
        {% csrf_token %}
        {% if event %}
          <input type="hidden" name="id" value="{{event.object_id}}"/>
        {% endif %}
        <label for="name">Name:</label><input name="event_name" required="required" maxlength="60" {% if event.event_name %}value="{{event.event_name}}"{% endif %}/><br/>
        <label for="location">Location:</label><input name="location" maxlength="60" {% if event.location %}value="{{event.location}}"{% endif %}/><br/>
        <label for="start_date">Starts:</label><input type="date" name="start_date" {% if event.start_date %}value="{{event.start_date.isoformat}}"{% endif %}/>
        <label for="end_date">Ends:</label><input type="date" name="end_date" {% if event.end_date %}value="{{event.end_date.isoformat}}"{% endif %}/><br/>
        <input type="submit" value="{% if event %}Modify{% else %}Add{% endif %}"/>
      </fieldset>
    </form>
  {% else %}
  <p><a href="{% url 'chess:login' %}">You need to be logged in to create new objects</a></p>
  {% endif %}
{% endblock %}

chess_openings/chs/templates/chs/event_search.html
{% extends "chs/base.html" %}

{% load staticfiles %}

{% block title %}search events{% endblock %}

{% block content %}
<h1>Event search </h1>
<form action="{% url 'chess:event_list' %}" method="get">
  <fieldset> <legend> Event search</legend>
    <label for="name">Name:</label><input name="name"/><br/>
    <label for="location">Location:</label><input name="location"/><br/>
    <label for="after">After:</label><input type="date" name="after"/>
    <label for="before">Before:</label><input type="date" name="before"/><br/>
    <input type="submit" value="Search"/>
  </fieldset>
</form>
{% endblock %}

chess_openings/chs/templates/chs/game_create.html
{% extends "chs/base.html" %}

{% load staticfiles %}

{% block title %}create game{% endblock %}

{% block head %}
  <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "js/chess.js" %}"></script>
  <script src="{% static "js/chessboard-0.3.0.js" %}"></script>
  <link rel="stylesheet" href="{% static "css/chessboard-0.3.0.css"%}"/>
{% endblock %}

{% block content %}
<h1>Game {% if game %} modification {% else %} creation{% endif %}</h1>
{% if request.session.account %}
<form action="{% url 'chess:game_add' %}" method="post">
  <fieldset>
    <legend>{% if game %} Game modification {% else %} New game {% endif %}</legend>
    {% csrf_token %}
    {% if game %}
      <input type="hidden" name="id" value="{{game.object_id}}"/>
    {% endif %}
    <div id="chessboard">
      <div id="board"></div>
      <input type="hidden" id="moves_input" name="moves"/>
      <ul class="move-menu">
        <li class="prev"><button type="button" onclick="undo()">Undo</button></li>
        <li class="next"><button type="button" onclick="reset_board()">Reset</button><br/></li>
      </ul>
    </div>
    <p id="moves_text"></p>
    <label for="result">Result:</label><select id="result_input" name="result">
      <option value="1-0">White wins (1-0)</option>
      <option value="0-1">Black wins (0-1)</option>
      <option value="1/2-1/2">Draw (1/2-1/2)</option>
      <option value="*" selected>Ongoing - Other (*)</option>
    </select>
    <script>
    {% if game.moves %}
    var moves = [
      {% for move in game.moves_san %}"{{move}}",{% endfor %}
    ];
    {% else %}
    var moves = [];
    {% endif %}
    var moves_len = moves.length;

    var game = new Chess();
    for (i = 0; i < moves_len; i++) {
      game.move(moves[i]);
    }

    var moves_text = document.getElementById("moves_text")
    var moves_input = document.getElementById("moves_input")
    var result_input = document.getElementById("result_input")

    function onDragStart(source, piece) {
      if (game.game_over() === true ||
          (game.turn() === 'w' && piece.search(/^b/) !== -1) ||
          (game.turn() === 'b' && piece.search(/^w/) !== -1)) {
        return false;
      }
    }

    function onDrop(source, target) {
      var move = game.move({
        from: source,
        to: target,
        promotion: 'q'
      });

      if (move === null) return 'snapback';
      updateStatus();
    }

    function onSnapEnd() {
      board.position(game.fen());
    }

    function updateStatus() {
      moves_text.innerHTML = game.pgn();
      moves_input.value = game.history({verbose: true}).map(
        m => m.from + m.to + (m.promotion ? m.promotion : "")
      );

      var value = "*";
      var force = false;
      if(game.game_over()) {
        force = true;
        if(game.in_checkmate()) {
          if(game.turn() === 'b') {
            value = "1-0";
          } else {
            value = "0-1";
          }
        } else {
          value = "1/2-1/2";
        }
      }

      for (i = 0; i < result_input.options.length; i++) {
        option = result_input.options[i];
        if(force && option.value !== value) option.disabled = true;
        else option.disabled = false;
      }
      result_input.value = value;
    }

    function undo() {
      game.undo();
      board.position(game.fen());
      updateStatus();
    }

    function reset_board() {
      game.reset();
      board.position(game.fen());
      updateStatus();
    }

    var cfg = {
      draggable: true,
      position: 'start',
      onDragStart: onDragStart,
      onDrop: onDrop,
      onSnapEnd: onSnapEnd
    };
    var board = ChessBoard('board', cfg);

    board.position(game.fen());
    updateStatus();
    {% if game.result %}
    result_input.value = "{{game.result}}";
    {% endif %}
    </script>
    <label for="white_first">White firstname:</label><input name="white_first" maxlength="50" {% if game.white %}value="{{game.white.firstname}}"{% endif %}/>
    <label for="white_last">White lastname:</label><input name="white_last" maxlength="50" {% if game.white %}value="{{game.white.lastname}}"{% endif %}/><br/>
    <label for="black_first">Black firstname:</label><input name="black_first" maxlength="50" {% if game.black %}value="{{game.black.firstname}}"{% endif %}/>
    <label for="black_lasrt">Black lastname:</label><input name="black_last" maxlength="50" {% if game.black %}value="{{game.black.lastname}}"{% endif %}/><br/>
    <label for="event">Event:</label><input name="event" maxlength="60"  {% if game.event %}value="{{game.event.event_name}}"{% endif %}/><br/>
    <label for="location">Site:</label><input name="location" maxlength="60" {% if game.location %}value="{{game.location}}"{% endif %}/><br/>
    <label for="date">Date:</label><input type="date" name="date" {% if game.start_date %}value="{{game.start_date.isoformat}}"{% endif %}/><br/>
    <input type="submit" value="{% if game %}Modify{% else %}Add{% endif %}"/>
  </fieldset>
</form>
{% if not game %}
<p>or</p>
<script>
var chess = new Chess();
function validate_pgn_form() {
  var pgn = document.forms["pgn_form"]["pgn"].value;
  if(!chess.load_pgn(pgn)) {
    alert("Invalid pgn file");
    return false;
  }
  return true;
}
</script>

<form name="pgn_form" action="{% url 'chess:game_add_pgn' %}" method="post" onsubmit="return validate_pgn_form()">
  <fieldset> <legend>Upload PGN file</legend>
    {% csrf_token %}
    <input type="file" name="pgn"/><br/>
    <input type="submit" value="Add from pgn" style="width: 150px"/>
  </fieldset>
</form>
{% endif %}
{% else %}
<p>You need to be logged in to create new objects</p>
{% endif %}
{% endblock %}

chess_openings/chs/templates/chs/game_detail.html
{% extends "chs/base.html" %}

{% load staticfiles %}

{% block title %}{{game.white}} vs {{game.black}}{% endblock %}

{% block head %}
  <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "js/chess.js" %}"></script>
  <script src="{% static "js/chessboard-0.3.0.js" %}"></script>
  <link rel="stylesheet" href="{% static "css/chessboard-0.3.0.css"%}"/>
{% endblock %}

{% block content %}
<h1>
{% if game.white %}
  <a href="{% url 'chess:player' game.white.object_id %}"> {{game.white}} </a>
{% else %}
  unknown
{% endif %}
vs
{% if game.black %}
  <a href="{% url 'chess:player' game.black.object_id %}"> {{game.black}} </a>
{% else %}
  unknown
{% endif %}
: {{game.result}}
</h1>
{% if game.event %}
  <a href="{% url 'chess:event' game.event.object_id %}"> {{game.event.event_name}} </a>,
{% endif %}
{% if game.location %}
  {{game.location}},
{% endif %}
{% if game.start_date %}
  {{game.start_date}}
{% endif %}

<div id="chessboard">
  <div id="board"></div>
  <ul class="move-menu">
    <li class="prev"> <button type="button" onclick="prev_move(); update()">prev</button> </li>
    <li class="reset"><button type="button" onclick="goto_move(0); update()">reset</button> </li>
    <li class="next"><button type="button" onclick="next_move(); update()">next</button> </li>
  </ul>
</div>
<p id="moves_text"></p>
<script>
var moves = [
  {% for move in game.moves_san %}"{{move}}",{% endfor %}
];
var moves_len = moves.length;

var game = new Chess();

var cfg = {
  position: 'start'
};
var board = ChessBoard('board', cfg);

function set_board_position(use_animation = true) {
  board.position(game.fen(), use_animation);
}

var current_move = 0;
function prev_move() {
  if (current_move > 0) {
    current_move--;
    game.undo();
  }
}
function next_move() {
  if (current_move < moves_len) {
    game.move(moves[current_move]);
    current_move++;
  }
}
function goto_move(i) {
  if (i >= 0 && i <= moves_len) {
    while(current_move < i) next_move();
    while(current_move > i) prev_move();
  }
}
function update(use_animation = true) {
  set_board_position(use_animation);
  set_moves_text();
}

function move_text(i) {
  return '<span onclick="goto_move(' + (i+1) + '); update()">' + moves[i] + '</span>';
}
function set_moves_text() {
  text = "";
  for (i=0; i<moves_len; i++) {
    prefix = "";
    if(!(i%2)) prefix = (i/2 + 1) + ". "
    str = move_text(i);
    if ((i+1) === current_move) str = str.bold();
    text += prefix + str + " ";
  }
  text += "{{game.result}}";
  document.getElementById("moves_text").innerHTML = text;
}
goto_move(moves_len);
update(false);
</script>

<h3>Openings</h3>
{% with opening_list=openings %}
{% include "chs/opening_table.html" %}
{% endwith %}

{% include "chs/comments.html" %}
{% if can_edit %}
<a href="{% url 'chess:game_edit' game.object_id %}">edit</a>
<a href="{% url 'chess:game_delete' game.object_id %}">delete</a>
{% endif %}
{% endblock %}

chess_openings/chs/templates/chs/game_list.html
{% extends "chs/base.html" %}

{% block title %}games{% endblock %}

{% block content %}
<h1>Games list</h1>
You can <a href="{% url 'chess:game_search' %}">search</a>
{% if request.session.account %}
  or <a href="{% url 'chess:game_create' %}">create</a>
{% endif %}
games.
<p>
  {{game_number}} matching results. <br/>
  white wins : {{white_wins}} ({{white_percent}}%) <br/>
  black wins : {{black_wins}} ({{black_percent}}%) <br/>
  draws : {{draws}} ({{draws_percent}}%) <br/>
</p>
{% include "chs/paginator.html" %}
{% include "chs/game_table.html" %}
{% include "chs/paginator.html" %}
{% endblock %}

chess_openings/chs/templates/chs/opening_detail.html
{% extends "chs/base.html" %}

{% load staticfiles %}

{% block title %}{{opening.opening_name}}{% endblock %}

{% block head %}
<script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
<script src="{% static "js/chess.js" %}"></script>
<script src="{% static "js/chessboard-0.3.0.js" %}"></script>
<link rel="stylesheet" href="{% static "css/chessboard-0.3.0.css"%}"/>
{% endblock %}

{% block content %}
<h1>{{opening.opening_name}}</h1>
<div id="chessboard">
  <div id="board"></div>
  <ul class="move-menu">
    <li class="prev"> <button type="button" onclick="prev_move(); update()">prev</button> </li>
    <li class="reset"><button type="button" onclick="goto_move(0); update()">reset</button> </li>
    <li class="next"><button type="button" onclick="next_move(); update()">next</button> </li>
  </ul>
</div>
<p id="moves_text"></p>
<script>
var moves = [
  {% for move in opening.moves_san %}"{{move}}",{% endfor %}
];
var moves_len = moves.length;

var game = new Chess();

var cfg = {
  position: 'start'
};
var board = ChessBoard('board', cfg);

function set_board_position(use_animation = true) {
  board.position(game.fen(), use_animation);
}

var current_move = 0;
function prev_move() {
  if (current_move > 0) {
    current_move--;
    game.undo();
  }
}
function next_move() {
  if (current_move < moves_len) {
    game.move(moves[current_move]);
    current_move++;
  }
}
function goto_move(i) {
  if (i >= 0 && i <= moves_len) {
    while(current_move < i) next_move();
    while(current_move > i) prev_move();
  }
}
function update(use_animation = true) {
  set_board_position(use_animation);
  set_moves_text();
}

function move_text(i) {
  return '<span onclick="goto_move(' + (i+1) + '); update()">' + moves[i] + '</span>';
}
function set_moves_text() {
  text = "";
  for (i=0; i<moves_len; i++) {
    prefix = "";
    if(!(i%2)) prefix = (i/2 + 1) + ". "
    str = move_text(i);
    if ((i+1) === current_move) str = str.bold();
    text += prefix + str + " ";
  }
  document.getElementById("moves_text").innerHTML = text;
}
goto_move(moves_len);
update(false);
</script>

<h3>Games</h3>
{% with game_list=opening_games %}
{% include "chs/game_table.html" %}
{% endwith %}
<a href="{% url 'chess:game_list' %}?opening={{opening.opening_name|urlencode}}">all games</a>

<h3>Variations</h3>
{% with opening_list=variations %}
{% include "chs/opening_table.html" %}
{% endwith %}

<h3>Variation of</h3>
{% with opening_list=variation_of %}
{% include "chs/opening_table.html" %}
{% endwith %}

{% include "chs/comments.html" %}
{% if can_edit %}
<a href="{% url 'chess:opening_edit' opening.object_id %}">edit</a>
<a href="{% url 'chess:opening_delete' opening.object_id %}">delete</a>
{% endif %}
{% endblock %}

chess_openings/chs/templates/chs/opening_list.html
{% extends "chs/base.html" %}

{% block title %}openings{% endblock %}

{% block content %}
<h1>Openings list</h1>
You can also <a href="{% url 'chess:opening_search' %}">search</a>
{% if request.session.account %}
  or <a href="{% url 'chess:opening_create' %}">create</a>
{% endif %}
openings.
{% include "chs/paginator.html" %}
{% include "chs/opening_table.html" %}
{% include "chs/paginator.html" %}
{% endblock %}

chess_openings/chs/templates/chs/player_detail.html
{% extends "chs/base.html" %}

{% block title %}{{player.firstname}} {{player.lastname}}{% endblock %}

{% block content %}
<h1>{{player.firstname}} {{player.lastname}}</h1>

{% if player.elo_rating %}Elo: {{player.elo_rating}}{% endif %}
{% if player.nationality %}, {{player.nationality}}{% endif %}

<h3>Games list</h3>
{% with game_list=player_games %}
{% include "chs/game_table.html" %}
{% endwith %}
<a href="{% url 'chess:game_list' %}?player={{player.lastname|urlencode}}">all games</a>

{% include "chs/comments.html" %}
{% if can_edit %}
<a href="{% url 'chess:player_edit' player.object_id %}">edit</a>
<a href="{% url 'chess:player_delete' player.object_id %}">delete</a>
{% endif %}
{% endblock %}